100%|█████████████████████████████████████████████████████████████████████████████████████▌| 199/200 [00:12<00:00, 17.74it/s]/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/peft/utils/other.py:716: UserWarning: Unable to fetch remote file due to the following error (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x76a394daae50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 369d33b8-336d-4630-ae4c-f6df929212f6)') - silently ignoring the lookup for the file config.json in gpt2.
  warnings.warn(                                                                                                             
{'eval_loss': 0.9589561223983765, 'eval_runtime': 0.6313, 'eval_samples_per_second': 677.935, 'eval_steps_per_second': 85.534, 'epoch': 1.0}
/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/peft/utils/save_and_load.py:246: UserWarning: Could not find a config file in gpt2 - will assume that the vocabulary was not modified.
  warnings.warn(
100%|██████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:22<00:00,  8.70it/s]
/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/peft/utils/other.py:716: UserWarning: Unable to fetch remote file due to the following error (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x76a386720610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 2129b06b-4392-4056-bd4d-c417bf3c8597)') - silently ignoring the lookup for the file config.json in gpt2.
{'eval_loss': 0.9448196291923523, 'eval_runtime': 0.615, 'eval_samples_per_second': 695.957, 'eval_steps_per_second': 87.808, 'epoch': 2.0}
{'train_runtime': 24.5434, 'train_samples_per_second': 130.381, 'train_steps_per_second': 8.149, 'train_loss': 1.1819711303710938, 'epoch': 2.0}
  warnings.warn(
/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/peft/utils/save_and_load.py:246: UserWarning: Could not find a config file in gpt2 - will assume that the vocabulary was not modified.
  warnings.warn(
/home/ckqsudo/code2024/CKQ_ACL2024/Control_Infer/SAE-simple/src/sentiment_lora_baseline/lora_ckpt/sentiment_pos2neg_lora_baseline
训练时间开销 25.581960678100586
